### ISSUE TITLE
Sharable configuration via URL

### ISSUE THREAD

**Issue by silverwind** [rytsh/repeatit#4]
Could be done by continously updating the URL hash to a base64 value:

```js
window.location.hash = btoa(JSON.stringify({template, input}))
```
Then, on page load check if `window.location.hash` decodes and fill the values. Won't work for excessively long URLs, but browsers should be able to handle URLs up to 32k characters long.

**Comment by rytsh** [comment]
That is a great idea, I am now adding this kind of feature! 🥳

**Comment by rytsh** [comment]
@silverwind, I implemented could you check now?

**Comment by silverwind** [comment]
Works great, thanks!
