### ISSUE TITLE
add Helm functions 

### ISSUE THREAD

**Issue by clemcvlcs** [rytsh/repeatit#6]
## Description 

It would be great to be able to use helm functions like 
`toYaml`, `fromJson` etc, in addition to sprig ones

**Comment by rytsh** [comment]
Hi @clemcvlcs , thanks for issue.
Yes I agree, I will add the helm functions.

**Comment by rytsh** [comment]
Hi @clemcvlcs, I copied this https://github.com/helm/helm/blob/main/pkg/engine/funcs.go inside of the project and set the default is helm.
I will close this issue after your confirmation.
