### ISSUE TITLE
Site seems broken?

### ISSUE THREAD

**Issue by MaxAnderson95** [rytsh/repeatit#7]
It doesn't seem like the site is rendering the results anymore? Even with a built-in example, the output box is completely empty:

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/2a20bd07-ace1-49cd-9048-483b4617c528">

It was working for me a few days ago, but I noticed v0.5.0 was release two days ago. I wonder if something in this new release broke rendering?

**Comment by MaxAnderson95** [comment]
Shortly after submitting the issue, it's now working as expected....

**Comment by rytsh** [comment]
Could be some problem on downloading wasm file, serving with github page.
Nice than closing ticket.
